# Generated by Django 2.2.1 on 2020-09-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('direccion', '0001_initial'),
        ('carro', '0009_auto_20200828_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.CharField(blank=True, max_length=120)),
                ('email_adicional', models.EmailField(blank=True, max_length=254, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.CarroCompra')),
                ('direccion_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_envio', to='direccion.Direccion')),
                ('direccion_facturacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_facturacion', to='direccion.Direccion')),
                ('facturacion_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.FacturacionProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('accountingDate', models.CharField(blank=True, max_length=4, null=True)),
                ('buyOrder', models.CharField(blank=True, max_length=26, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=16, null=True)),
                ('cardExpirationDate', models.CharField(blank=True, max_length=4, null=True)),
                ('sharesAmount', models.CharField(blank=True, max_length=10, null=True)),
                ('sharesNumber', models.CharField(blank=True, max_length=2, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('commerceCode', models.CharField(blank=True, max_length=12, null=True)),
                ('authorizationCode', models.CharField(blank=True, max_length=6, null=True)),
                ('paymentTypeCode', models.CharField(blank=True, max_length=3, null=True)),
                ('responseCode', models.CharField(blank=True, max_length=2, null=True)),
                ('sessionId', models.CharField(blank=True, max_length=61, null=True)),
                ('transactionDate', models.CharField(blank=True, max_length=6, null=True)),
                ('urlRedirection', models.CharField(blank=True, max_length=256, null=True)),
                ('vci', models.CharField(blank=True, max_length=4, null=True)),
                ('facturacion_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.FacturacionProfile')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orden.OrdenCompra')),
            ],
        ),
    ]
