# Generated by Django 2.2.1 on 2020-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='email_adicional',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
