# Generated by Django 2.2.1 on 2020-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='orden_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
