# Generated by Django 2.2.1 on 2020-09-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='vci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
