# Generated by Django 2.2.1 on 2020-09-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_auto_20200901_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='vci',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
