# Generated by Django 2.2.1 on 2020-08-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20200804_0057'),
        ('orden', '0002_auto_20200803_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='facturacion_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.FacturacionProfile'),
        ),
    ]
