# Generated by Django 2.2.1 on 2020-08-31 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_ordencompra_email_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTBK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('accountingDate', models.CharField(blank=True, max_length=200, null=True)),
                ('buyOrder', models.CharField(blank=True, max_length=200, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('cardExpirationDate', models.CharField(blank=True, max_length=200, null=True)),
                ('sharesAmount', models.CharField(blank=True, max_length=200, null=True)),
                ('sharesNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('commerceCode', models.CharField(blank=True, max_length=200, null=True)),
                ('authorizationCode', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentTypeCode', models.CharField(blank=True, max_length=200, null=True)),
                ('responseCode', models.CharField(blank=True, max_length=200, null=True)),
                ('sessionId', models.CharField(blank=True, max_length=200, null=True)),
                ('transactionDate', models.CharField(blank=True, max_length=200, null=True)),
                ('urlRedirection', models.CharField(blank=True, max_length=200, null=True)),
                ('VCI', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orden.OrdenCompra')),
            ],
        ),
    ]
