# Generated by Django 2.2.1 on 2020-09-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_auto_20200901_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='transactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
