# Generated by Django 2.2.1 on 2020-08-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        ('orden', '0003_auto_20200804_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_envio', to='direccion.Direccion'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='direccion_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_facturacion', to='direccion.Direccion'),
        ),
    ]
