# Generated by Django 2.2.1 on 2020-09-02 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_auto_20200901_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('initTransaction', 'initTransaction'), ('getTransactionResult', 'getTransactionResult'), ('acknowledgeTransaction', 'acknowledgeTransaction'), ('rechazoTransaccion_1', 'rechazoTransaccion_1'), ('rechazoTransaccion_2', 'rechazoTransaccion_2'), ('errorTransaccion', 'errorTransaccion'), ('rechazoEmisor', 'rechazoEmisor'), ('rechazoPosibleFraude', 'rechazoPosibleFraude')], default='initTransaction', max_length=30)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orden.OrdenCompra')),
            ],
        ),
    ]
