# Generated by Django 2.2.1 on 2020-09-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0007_auto_20200903_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcobro',
            name='estado',
            field=models.CharField(choices=[('initTransaction', 'initTransaction'), ('getTransactionResult', 'getTransactionResult'), ('acknowledgeTransaction', 'acknowledgeTransaction'), ('rechazoTransaccion_1', 'rechazoTransaccion_1'), ('rechazoTransaccion_2', 'rechazoTransaccion_2'), ('errorTransaccion', 'errorTransaccion'), ('rechazoEmisor', 'rechazoEmisor'), ('rechazoPosibleFraude', 'rechazoPosibleFraude'), ('desconocido', 'desconocido'), ('exitoso', 'existoso')], default='initTransaction', max_length=30),
        ),
    ]
