# Generated by Django 2.2.1 on 2020-09-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0001_initial'),
        ('carro', '0009_auto_20200828_2120'),
        ('orden', '0008_auto_20200903_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasCompradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rembolsado', models.BooleanField(default=False)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('facturacion_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.FacturacionProfile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.ItemCarroCompra')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
