# Generated by Django 2.2.1 on 2020-09-06 20:15

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import orden.models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0010_auto_20200903_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasCompradasITicketFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/rodrigoparada/Desktop/Proyectos/Proyectos Django/TOCA/protected_media'), upload_to=orden.models.upload_ticket_file_loc)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden.EntradasCompradas')),
            ],
        ),
    ]
