# Generated by Django 2.2.1 on 2020-09-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0011_entradascompradasiticketfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradascompradasiticketfile',
            old_name='item',
            new_name='entrada_comprada',
        ),
    ]
