# Generated by Django 2.2.1 on 2020-09-06 23:02

import django.core.files.storage
from django.db import migrations, models
import orden.models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0012_auto_20200906_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradascompradas',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/rodrigoparada/Desktop/Proyectos/Proyectos Django/TOCA/protected_media'), upload_to=orden.models.upload_ticket_file_loc),
        ),
        migrations.DeleteModel(
            name='EntradasCompradasITicketFile',
        ),
    ]
