# Generated by Django 2.2.1 on 2020-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0015_auto_20200910_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
