# Generated by Django 2.2.1 on 2020-09-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0017_entradascompradas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradascompradas',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
