# Generated by Django 2.2.1 on 2020-09-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0020_auto_20200921_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradascompradas',
            name='slug',
        ),
    ]
