# Generated by Django 2.2.1 on 2020-09-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0021_remove_entradascompradas_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradascompradas',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
