# Generated by Django 2.2.1 on 2020-10-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden', '0022_entradascompradas_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnulacionEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviadatbk', 'Enviada a Transbank'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('entradas_compradas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden.EntradasCompradas')),
            ],
        ),
    ]
