# Generated by Django 2.2.1 on 2020-10-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anulaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anulacionentrada',
            name='metodo_reembolso',
            field=models.CharField(choices=[('credito', 'Tarjeta de Crédito'), ('debito', 'Tarjeta de Debito')], default='credito', max_length=20),
        ),
        migrations.AddField(
            model_name='anulacionentrada',
            name='motivo',
            field=models.CharField(choices=[('artista', 'Suspendido por Artista'), ('anfitrion', 'Anfitrio canceló Lugar'), ('otro', 'Otro')], default='artista', max_length=20),
        ),
    ]
