# Generated by Django 2.2.1 on 2020-10-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anulaciones', '0002_auto_20201014_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anulacionentrada',
            name='motivo',
        ),
    ]
