# Generated by Django 2.2.1 on 2020-10-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anulaciones', '0004_auto_20201014_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anulacionentrada',
            name='cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden.Cobro'),
        ),
    ]
