# Generated by Django 2.2.1 on 2020-09-07 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('es_artista', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(default=0)),
                ('digitoVerificador', models.CharField(default='0', max_length=1)),
                ('num_celular', models.CharField(default=0, max_length=50)),
                ('banco', models.CharField(choices=[('012', 'BANCO DEL ESTADO DE CHILE'), ('001', 'BANCO DE CHILE'), ('009', 'BANCO INTERNACIONAL'), ('014', 'SCOTIABANK CHILE'), ('016', 'BANCO DE CREDITO E INVERSIONES'), ('028', 'BANCO BICE'), ('031', 'HSBC BANK (CHILE)'), ('037', 'BANCO SANTANDER-CHILE'), ('039', 'ITAÚ CORPBANCA'), ('049', 'BANCO SECURITY'), ('051', 'BANCO FALABELLA'), ('053', 'BANCO RIPLEY'), ('055', 'BANCO CONSORCIO'), ('504', 'SCOTIABANK AZUL (ex BANCO BILBAO VIZCAYA ARGENTARIA, CHILE (BBVA))'), ('059', 'BANCO BTG PACTUAL CHILE')], default='012', max_length=200)),
                ('num_cuenta', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('001', 'Cuenta Corriente'), ('002', 'Cuenta de Ahorro'), ('003', 'Cuenta Vista'), ('004', 'Cuenta Chequera Electrónica'), ('005', 'Cuenta RUT')], default='001', max_length=200)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.PerfilUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
