# Generated by Django 2.2.1 on 2020-09-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilartista',
            name='perfil',
        ),
    ]
