# Generated by Django 2.2.1 on 2020-09-07 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfilartista_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilartista',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
