# Generated by Django 2.2.1 on 2020-09-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20200907_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='es_artista',
        ),
    ]
