# Generated by Django 2.2.1 on 2020-08-15 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tocata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodeitems', models.IntegerField(default=0)),
                ('totalapagar', models.IntegerField(default=0)),
                ('mediodepago', models.CharField(choices=[('WP', 'Webpay')], default='WP', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTocata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.Orden')),
                ('tocata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.Tocata')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTBK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('accountingDate', models.CharField(blank=True, max_length=200, null=True)),
                ('buyOrder', models.CharField(blank=True, max_length=200, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('cardExpirationDate', models.CharField(blank=True, max_length=200, null=True)),
                ('sharesAmount', models.CharField(blank=True, max_length=200, null=True)),
                ('sharesNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('commerceCode', models.CharField(blank=True, max_length=200, null=True)),
                ('authorizationCode', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentTypeCode', models.CharField(blank=True, max_length=200, null=True)),
                ('responseCode', models.CharField(blank=True, max_length=200, null=True)),
                ('sessionId', models.CharField(blank=True, max_length=200, null=True)),
                ('transactionDate', models.CharField(blank=True, max_length=200, null=True)),
                ('urlRedirection', models.CharField(blank=True, max_length=200, null=True)),
                ('VCI', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.Orden')),
                ('tocata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.Tocata')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
