# Generated by Django 2.2.1 on 2020-07-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
