# Generated by Django 2.2.1 on 2020-07-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0003_orden_ordentocata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentocata',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
