# Generated by Django 2.2.1 on 2020-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0004_ordentocata_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentocata',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
