# Generated by Django 2.2.1 on 2020-07-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0005_ordentocata_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
