# Generated by Django 2.2.1 on 2020-07-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0006_orden_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.Orden'),
        ),
    ]
