# Generated by Django 2.2.1 on 2020-07-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0007_carro_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTBK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountingDate', models.CharField(blank=True, max_length=200)),
                ('buyOrder', models.CharField(blank=True, max_length=200)),
                ('cardNumber', models.CharField(blank=True, max_length=200)),
                ('cardExpirationDate', models.CharField(blank=True, max_length=200)),
                ('sharesAmount', models.CharField(blank=True, max_length=200)),
                ('sharesNumber', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=200)),
                ('commerceCode', models.CharField(blank=True, max_length=200)),
                ('authorizationCode', models.CharField(blank=True, max_length=200)),
                ('paymentTypeCode', models.CharField(blank=True, max_length=200)),
                ('responseCode', models.CharField(blank=True, max_length=200)),
                ('sessionId', models.CharField(blank=True, max_length=200)),
                ('transactionDate', models.CharField(blank=True, max_length=200)),
                ('urlRedirection', models.CharField(blank=True, max_length=200)),
                ('VCI', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
