# Generated by Django 2.2.1 on 2020-07-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0009_auto_20200717_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentbk',
            name='orden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='cobro.Orden'),
            preserve_default=False,
        ),
    ]
