# Generated by Django 2.2.1 on 2020-07-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobro', '0010_ordentbk_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentbk',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
