# Generated by Django 2.2.1 on 2020-08-15 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_direccion', models.CharField(choices=[('facturacion', 'Facturacion'), ('envio', 'Envio')], max_length=100)),
                ('nombre_calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('ciudad', models.CharField(blank=True, max_length=200)),
                ('pais', models.CharField(default='Chile', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=20)),
                ('otros', models.CharField(blank=True, max_length=20)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Comuna')),
                ('facturacion_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.FacturacionProfile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region')),
            ],
        ),
    ]
