# Generated by Django 2.2.1 on 2020-08-15 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tocataabierta', '0001_initial'),
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugaresTocata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('elegido', 'Elegido'), ('noelegido', 'No Elegido'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('completado', 'Completado'), ('borrado', 'Borrado')], default='pendiente', max_length=2)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Lugar')),
                ('tocataabierta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tocataabierta.TocataAbierta')),
            ],
        ),
    ]
