# Generated by Django 2.2.1 on 2020-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestaslugar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarestocata',
            name='estado',
            field=models.CharField(choices=[('elegido', 'Elegido'), ('noelegido', 'No Elegido'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('completado', 'Completado'), ('borrado', 'Borrado')], default='pendiente', max_length=20),
        ),
    ]
