# Generated by Django 2.2.1 on 2020-09-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='subscrited',
            new_name='subscribed',
        ),
    ]
