# Generated by Django 2.2.1 on 2020-08-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
