# Generated by Django 2.2.1 on 2020-08-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20200812_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellido',
        ),
        migrations.AddField(
            model_name='user',
            name='ßapellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
