# Generated by Django 2.2.1 on 2020-08-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20200812_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ßapellido',
            new_name='apellido',
        ),
    ]
