# Generated by Django 2.2.1 on 2020-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_emailactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_artista',
            field=models.BooleanField(default=False),
        ),
    ]
