# Generated by Django 2.2.1 on 2020-09-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_user_es_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='es_artista',
        ),
    ]
