# Generated by Django 2.2.1 on 2020-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_remove_user_es_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='musico',
            field=models.BooleanField(default=False),
        ),
    ]
