# Generated by Django 2.2.1 on 2020-04-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200427_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(default=0)),
                ('banco', models.CharField(choices=[('012', 'BANCO DEL ESTADO DE CHILE'), ('001', 'BANCO DE CHILE'), ('009', 'BANCO INTERNACIONAL'), ('014', 'SCOTIABANK CHILE'), ('016', 'BANCO DE CREDITO E INVERSIONES'), ('028', 'BANCO BICE'), ('031', 'HSBC BANK (CHILE)'), ('037', 'BANCO SANTANDER-CHILE'), ('039', 'ITAÚ CORPBANCA'), ('049', 'BANCO SECURITY'), ('051', 'BANCO FALABELLA'), ('053', 'BANCO RIPLEY'), ('055', 'BANCO CONSORCIO'), ('504', 'SCOTIABANK AZUL (ex BANCO BILBAO VIZCAYA ARGENTARIA, CHILE (BBVA))'), ('059', 'BANCO BTG PACTUAL CHILE')], default='012', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
    ]
