# Generated by Django 2.2.1 on 2020-04-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuarioartista'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioartista',
            name='digitoVerificador',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
