# Generated by Django 2.2.1 on 2020-04-29 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuarioartista_digitoverificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioartista',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
