# Generated by Django 2.2.1 on 2020-04-29 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0004_artista_habilidades'),
        ('usuario', '0005_auto_20200429_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioartista',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista'),
        ),
    ]
