# Generated by Django 2.2.1 on 2020-04-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuarioartista_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioartista',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista'),
        ),
    ]
