# Generated by Django 2.2.1 on 2020-04-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200429_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioartista',
            name='num_celular',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
