# Generated by Django 2.2.1 on 2020-04-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuarioartista_num_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioartista',
            name='num_cuenta',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
