# Generated by Django 2.2.1 on 2020-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20200430_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioartista',
            name='num_celular',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
