# Generated by Django 2.2.1 on 2020-06-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20200430_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioartista',
            name='num_cuenta',
            field=models.CharField(max_length=100),
        ),
    ]
