# Generated by Django 2.2.1 on 2020-08-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('testimonio', models.CharField(blank=True, max_length=120)),
                ('objetivo', models.CharField(choices=[('AR', 'Artistas'), ('US', 'Usuarios')], default='US', max_length=2)),
                ('estado', models.CharField(choices=[('DI', 'Disponible'), ('ND', 'No Disponible')], default='DI', max_length=2)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista')),
            ],
        ),
    ]
