# Generated by Django 2.2.1 on 2020-08-15 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionTocatasIntimas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
                ('objetivo', models.CharField(choices=[('artistas', 'Artistas'), ('usuarios', 'Usuarios')], default='usuarios', max_length=20)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('testimonio', models.CharField(blank=True, max_length=120)),
                ('objetivo', models.CharField(choices=[('artistas', 'Artistas'), ('usuarios', 'Usuarios')], default='usuarios', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('nodisponible', 'No Disponible')], default='disponible', max_length=20)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista')),
            ],
        ),
    ]
