# Generated by Django 2.2.1 on 2020-08-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonio',
            name='slug',
        ),
    ]
