# Generated by Django 2.2.1 on 2020-06-22 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonios',
            name='estado',
            field=models.CharField(choices=[('DI', 'Disponible'), ('ND', 'No Disponible')], default='DI', max_length=2),
        ),
        migrations.AddField(
            model_name='testimonios',
            name='fecha_actua',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonios',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonios',
            name='objetico',
            field=models.CharField(choices=[('AR', 'Artistas'), ('US', 'Usuarios')], default='US', max_length=2),
        ),
    ]
