# Generated by Django 2.2.1 on 2020-08-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_descripciontocatasintimas_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripciontocatasintimas',
            name='icono',
            field=models.CharField(default='fa fa-users', max_length=20),
        ),
    ]
