# Generated by Django 2.2.1 on 2020-06-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200622_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonios',
            old_name='Testimonio',
            new_name='testimonio',
        ),
    ]
