# Generated by Django 2.2.1 on 2020-08-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_descripciontocatasintimas_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripciontocatasintimas',
            name='icono',
            field=models.CharField(default='fa fa-users', max_length=50),
        ),
    ]
