# Generated by Django 2.2.1 on 2020-06-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200622_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonios',
            name='testimonio',
            field=models.TextField(blank=True),
        ),
    ]
