# Generated by Django 2.2.1 on 2020-06-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200622_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonios',
            name='testimonio',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
