# Generated by Django 2.2.1 on 2020-06-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200622_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonios',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/testimonios/%Y/%m/%d/'),
        ),
    ]
