# Generated by Django 2.2.1 on 2020-08-11 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('foto_1920_1280', models.ImageField(blank=True, upload_to='fotos/artistas/')),
                ('foto_525_350', models.ImageField(blank=True, upload_to='fotos/artistas/')),
                ('descripción', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=200)),
                ('link_facebook', models.URLField(blank=True)),
                ('link_twitter', models.URLField(blank=True)),
                ('link_instagram', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('DI', 'Disponible'), ('ND', 'No Disponible')], default='DI', max_length=2)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
                ('cualidades', models.ManyToManyField(blank=True, to='artista.Cualidad')),
                ('estilos', models.ManyToManyField(blank=True, to='artista.Estilo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
