# Generated by Django 2.2.1 on 2020-01-20 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto1', models.ImageField(blank=True, upload_to='fotos/artistas/%Y/%m/%d/')),
                ('foto2', models.ImageField(blank=True, upload_to='fotos/artistas/%Y/%m/%d/')),
                ('foto3', models.ImageField(blank=True, upload_to='fotos/artistas/%Y/%m/%d/')),
                ('foto4', models.ImageField(blank=True, upload_to='fotos/artistas/%Y/%m/%d/')),
                ('descripción', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('DI', 'Disponible'), ('ND', 'No Disponible')], default='DI', max_length=2)),
                ('fecha_crea', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_actua', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
