# Generated by Django 2.2.1 on 2020-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0002_artista_foto_525_350'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='link_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='link_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='link_twitter',
            field=models.URLField(blank=True),
        ),
    ]
