# Generated by Django 2.2.1 on 2020-04-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0003_auto_20200415_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='habilidades',
            field=models.TextField(blank=True),
        ),
    ]
