# Generated by Django 2.2.1 on 2020-05-26 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artista', '0004_artista_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artista',
            name='fecha_actua',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
