# Generated by Django 2.2.1 on 2020-07-02 03:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0005_auto_20200526_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto_380_507',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[525, 350], upload_to='fotos/lugares/%Y/%m/%d/'),
        ),
    ]
