# Generated by Django 2.2.1 on 2020-07-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0006_artista_foto_380_507'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='estilos',
            field=models.TextField(blank=True),
        ),
    ]
