# Generated by Django 2.2.1 on 2020-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0007_artista_estilos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
