# Generated by Django 2.2.1 on 2020-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0008_auto_20200729_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
