# Generated by Django 2.2.1 on 2020-07-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0010_estilo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='estilos',
        ),
        migrations.AddField(
            model_name='artista',
            name='estilos',
            field=models.ManyToManyField(blank=True, to='artista.Estilo'),
        ),
    ]
