# Generated by Django 2.2.1 on 2020-07-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0011_auto_20200729_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actua', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artista',
            name='habilidades',
        ),
        migrations.AddField(
            model_name='artista',
            name='cualidades',
            field=models.ManyToManyField(blank=True, to='artista.Cualidad'),
        ),
    ]
