# Generated by Django 2.2.1 on 2020-07-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0012_auto_20200729_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='foto1',
            new_name='foto_1920_1280',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='foto4',
        ),
    ]
