# Generated by Django 2.2.1 on 2020-07-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0013_auto_20200729_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='foto_380_507',
        ),
    ]
