# Generated by Django 2.2.1 on 2020-07-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0014_remove_artista_foto_380_507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='foto_1920_1280',
            field=models.ImageField(blank=True, upload_to='fotos/artistas/'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='foto_525_350',
            field=models.ImageField(blank=True, upload_to='fotos/artistas/'),
        ),
    ]
