# Generated by Django 2.2.1 on 2020-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0015_auto_20200730_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
