# Generated by Django 2.2.1 on 2020-01-20 19:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediosDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('plataforma', models.CharField(choices=[('ON', 'En Linea'), ('CA', 'Fuera de línea')], default='ON', max_length=2)),
                ('moneda', models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dolar US')], default='CLP', max_length=3)),
                ('ubicacion', models.CharField(choices=[('CL', 'Chile'), ('IN', 'Internacional')], default='CL', max_length=2)),
                ('formas_de_pago', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tocata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripción', models.TextField(blank=True)),
                ('costo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('fecha_actu', models.DateTimeField(blank=True)),
                ('fecha_crea', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lugar_def', models.CharField(choices=[('CE', 'Cerrada'), ('AB', 'Abierta')], default='CE', max_length=2)),
                ('asistentes_total', models.IntegerField()),
                ('asistentes_min', models.IntegerField()),
                ('asistentes_max', models.IntegerField()),
                ('flayer', models.ImageField(blank=True, upload_to='fotos/flayers/%Y/%m/%d/')),
                ('estado', models.CharField(choices=[('IN', 'Inicial'), ('PU', 'Publicado'), ('SU', 'Suspendido'), ('AP', 'Aplazado'), ('CN', 'Confirmado'), ('CM', 'Completado')], default='IN', max_length=2)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='CompraTocata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AC', 'Activa'), ('PA', 'Parcialmente Comprometida'), ('FA', 'Fallida'), ('AB', 'Abortada'), ('CO', 'Comprometida')], default='AC', max_length=2)),
                ('fecha_actu', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_crea', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mediosdepago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.MediosDePago')),
                ('tocata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.Tocata')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
