# Generated by Django 2.2.1 on 2020-04-13 18:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocata',
            name='flayer_380_507',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[380, 507], upload_to='fotos/lugares/%Y/%m/%d/'),
        ),
    ]
