# Generated by Django 2.2.1 on 2020-09-04 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TocataTicketFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tocata/ticket/')),
                ('tocata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tocata.Tocata')),
            ],
        ),
    ]
