# Generated by Django 2.2.1 on 2020-04-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0002_tocata_flayer_380_507'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocata',
            name='evaluacion',
            field=models.IntegerField(choices=[(1, 'Muy Mala'), (2, 'Mala'), (3, 'Regular'), (4, 'Buena'), (5, 'Muy Buena')], default=3),
        ),
    ]
