# Generated by Django 2.2.1 on 2020-09-04 14:54

from django.db import migrations, models
import django_resized.forms
import tocata.models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0002_tocataticketfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='flayer_1920_1280',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_1920_1280.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to=tocata.models.upload_tocata_flayer_file_loc),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='flayer_380_507',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_380_507.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[380, 507], upload_to=tocata.models.upload_tocata_flayer_file_loc),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='flayer_original',
            field=models.ImageField(blank=True, default='fotos/defecto/imagen_original.jpg', upload_to=tocata.models.upload_tocata_flayer_file_loc),
        ),
        migrations.AlterField(
            model_name='tocataticketfile',
            name='file',
            field=models.FileField(upload_to=tocata.models.upload_tocata_ticket_file_loc),
        ),
    ]
