# Generated by Django 2.2.1 on 2020-04-17 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0004_auto_20200415_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
