# Generated by Django 2.2.1 on 2020-09-24 14:50

from django.db import migrations
import django_resized.forms
import tocata.models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0005_auto_20200923_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocata',
            name='flayer_1920_1280',
        ),
        migrations.AlterField(
            model_name='tocata',
            name='flayer_380_507',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_380_507.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[380, 507], upload_to=tocata.models.upload_tocata_flayer_file_loc),
        ),
    ]
