# Generated by Django 2.2.1 on 2020-09-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0006_auto_20200924_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocata',
            name='flayer_original',
        ),
    ]
