# Generated by Django 2.2.1 on 2020-04-17 02:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0006_auto_20200417_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocata',
            name='flayer',
        ),
        migrations.AddField(
            model_name='tocata',
            name='flayer_1920_1280',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/'),
        ),
    ]
