# Generated by Django 2.2.1 on 2020-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0007_remove_tocata_flayer_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='asistentes_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
