# Generated by Django 2.2.1 on 2020-10-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0008_auto_20201012_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='estado',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('publicado', 'Publicado'), ('suspendido', 'Suspendido'), ('confirmado', 'Confirmado'), ('vendido', 'Vendido'), ('completado', 'Completado'), ('borrado', 'Borrado')], default='inicial', max_length=20),
        ),
    ]
