# Generated by Django 2.2.1 on 2020-05-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0009_tocata_flayer_oroginal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tocata',
            old_name='flayer_oroginal',
            new_name='flayer_original',
        ),
    ]
