# Generated by Django 2.2.1 on 2020-10-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0010_tocata_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocata',
            name='motivo',
        ),
    ]
