# Generated by Django 2.2.1 on 2020-05-11 02:02

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0011_auto_20200509_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='flayer_1920_1280',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_1920_1280.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='flayer_380_507',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_380_507.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[380, 507], upload_to='fotos/lugares/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='flayer_original',
            field=models.ImageField(blank=True, default='fotos/defecto/imagen_original.jpg', upload_to='fotos/tocatas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Lugar'),
        ),
    ]
