# Generated by Django 2.2.1 on 2020-05-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0012_auto_20200511_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Lugar'),
        ),
    ]
