# Generated by Django 2.2.1 on 2020-05-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0008_comuna_region'),
        ('tocata', '0013_auto_20200511_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugaresTocata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Lugar')),
                ('tocata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.Tocata')),
            ],
        ),
    ]
