# Generated by Django 2.2.1 on 2020-05-12 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0014_lugarestocata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarestocata',
            name='estado',
            field=models.CharField(choices=[('EL', 'Elegido'), ('NE', 'No Elegido')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='lugarestocata',
            name='fecha_actu',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lugarestocata',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
