# Generated by Django 2.2.1 on 2020-05-12 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tocata', '0015_auto_20200512_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarestocata',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
