# Generated by Django 2.2.1 on 2020-05-13 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0016_lugarestocata_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='asistentes_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='asistentes_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='costo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='evaluacion',
            field=models.IntegerField(choices=[(0, 'No Evaluada'), (1, 'Muy Mala'), (2, 'Mala'), (3, 'Regular'), (4, 'Buena'), (5, 'Muy Buena')], default=0),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='fecha_actu',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
