# Generated by Django 2.2.1 on 2020-05-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0011_auto_20200513_0148'),
        ('tocata', '0017_auto_20200513_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocata',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Comuna'),
        ),
        migrations.AddField(
            model_name='tocata',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region'),
        ),
    ]
