# Generated by Django 2.2.1 on 2020-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0018_auto_20200513_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='estado',
            field=models.CharField(choices=[('IN', 'Inicial'), ('PU', 'Publicado'), ('SU', 'Suspendido'), ('AP', 'Aplazado'), ('CN', 'Confirmado'), ('CM', 'Completado'), ('BO', 'Borrado')], default='IN', max_length=2),
        ),
    ]
