# Generated by Django 2.2.1 on 2020-06-24 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0017_auto_20200624_0240'),
        ('artista', '0005_auto_20200526_0344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tocata', '0019_auto_20200526_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocata',
            name='lugar_def',
        ),
        migrations.CreateModel(
            name='TocataAbierta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripción', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('asistentes_min', models.IntegerField()),
                ('flayer_original', models.ImageField(blank=True, default='fotos/defecto/imagen_original.jpg', upload_to='fotos/tocatas/%Y/%m/%d/')),
                ('flayer_1920_1280', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_1920_1280.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('flayer_380_507', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_380_507.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[380, 507], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('estado', models.CharField(choices=[('IN', 'Inicial'), ('PU', 'Publicado'), ('SU', 'Suspendido'), ('AP', 'Aplazado'), ('CN', 'Confirmado'), ('CM', 'Completado'), ('BO', 'Borrado')], default='IN', max_length=2)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Comuna')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
