# Generated by Django 2.2.1 on 2020-06-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0020_auto_20200624_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocataabierta',
            name='tocata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.Tocata'),
        ),
        migrations.AlterField(
            model_name='tocata',
            name='estado',
            field=models.CharField(choices=[('PU', 'Publicado'), ('SU', 'Suspendido'), ('CN', 'Confirmado'), ('VE', 'Vendido'), ('CM', 'Completado'), ('BO', 'Borrado')], default='PU', max_length=2),
        ),
        migrations.AlterField(
            model_name='tocataabierta',
            name='estado',
            field=models.CharField(choices=[('PU', 'Publicado'), ('SU', 'Suspendido'), ('CN', 'Confirmado'), ('BO', 'Borrado')], default='PU', max_length=2),
        ),
    ]
