# Generated by Django 2.2.1 on 2020-06-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0021_auto_20200624_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompraTocata',
        ),
        migrations.DeleteModel(
            name='MediosDePago',
        ),
    ]
