# Generated by Django 2.2.1 on 2020-06-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0025_auto_20200625_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugarestocata',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='lugarestocata',
            name='tocata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.TocataAbierta'),
        ),
    ]
