# Generated by Django 2.2.1 on 2020-06-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0026_auto_20200626_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugarestocata',
            old_name='tocata',
            new_name='tocataabierta',
        ),
    ]
