# Generated by Django 2.2.1 on 2020-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0030_auto_20200627_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarestocata',
            name='estado',
            field=models.CharField(choices=[('EL', 'Elegido'), ('NE', 'No Elegido'), ('PE', 'Pendiente'), ('CA', 'Cancelada'), ('CM', 'Completado')], default='PE', max_length=2),
        ),
    ]
