# Generated by Django 2.2.1 on 2020-06-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0031_auto_20200629_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarestocata',
            name='estado',
            field=models.CharField(choices=[('EL', 'Elegido'), ('NE', 'No Elegido'), ('PE', 'Pendiente'), ('CA', 'Cancelado'), ('CM', 'Completado'), ('BO', 'Borrado')], default='PE', max_length=2),
        ),
    ]
