# Generated by Django 2.2.1 on 2020-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0032_auto_20200629_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocataabierta',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
