# Generated by Django 2.2.1 on 2020-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0033_tocataabierta_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
