# Generated by Django 2.2.1 on 2020-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0035_auto_20200722_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocataabierta',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
