# Generated by Django 2.2.1 on 2020-07-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0037_remove_tocataabierta_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocataabierta',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
