# Generated by Django 2.2.1 on 2020-07-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0040_tocata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocata',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
