# Generated by Django 2.2.1 on 2020-07-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0042_auto_20200726_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocataabierta',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
