# Generated by Django 2.2.1 on 2020-07-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0017_auto_20200731_1746'),
        ('tocata', '0043_tocataabierta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocata',
            name='estilos',
            field=models.ManyToManyField(blank=True, to='artista.Estilo'),
        ),
        migrations.AddField(
            model_name='tocataabierta',
            name='estilos',
            field=models.ManyToManyField(blank=True, to='artista.Estilo'),
        ),
    ]
