# Generated by Django 2.2.1 on 2020-01-20 19:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField(default=0)),
                ('ciudad', models.CharField(default='Santiago', max_length=200)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('descripción', models.TextField(blank=True)),
                ('capacidad', models.IntegerField(default=0)),
                ('foto1', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('foto2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('foto3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('foto4', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('estado', models.CharField(choices=[('DI', 'Disponible'), ('ND', 'No Disponible')], default='DI', max_length=2)),
                ('fecha_crea', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_actua', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Comuna')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Provincia')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Provincia'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region'),
        ),
    ]
