# Generated by Django 2.2.1 on 2020-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='evaluacion',
        ),
        migrations.AlterField(
            model_name='lugar',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('noDisponible', 'No Disponible')], default='disponible', max_length=20),
        ),
    ]
