# Generated by Django 2.2.1 on 2020-05-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='foto1',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='foto4',
        ),
    ]
