# Generated by Django 2.2.1 on 2020-05-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0002_auto_20200501_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='evaluacion',
            field=models.IntegerField(choices=[(1, 'Muy Mala'), (2, 'Mala'), (3, 'Regular'), (4, 'Buena'), (5, 'Muy Buena')], default=3),
        ),
    ]
