# Generated by Django 2.2.1 on 2020-05-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0004_remove_comuna_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region'),
        ),
    ]
