# Generated by Django 2.2.1 on 2020-05-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0005_comuna_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
    ]
