# Generated by Django 2.2.1 on 2020-05-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0008_comuna_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='evaluacion',
            field=models.IntegerField(choices=[(0, 'No Evaluada'), (1, 'Muy Mala'), (2, 'Mala'), (3, 'Regular'), (4, 'Buena'), (5, 'Muy Buena')], default=0),
        ),
    ]
