# Generated by Django 2.2.1 on 2020-05-13 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0009_auto_20200513_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Comuna'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Provincia'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
