# Generated by Django 2.2.1 on 2020-05-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0010_auto_20200513_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='fecha_actua',
        ),
        migrations.AddField(
            model_name='lugar',
            name='fecha_actu',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='pais',
            field=models.CharField(default='Chile', max_length=100),
        ),
    ]
