# Generated by Django 2.2.1 on 2020-06-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0011_auto_20200513_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='departamento',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
