# Generated by Django 2.2.1 on 2020-06-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0012_lugar_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='block',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lugar',
            name='villa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='ciudad',
            field=models.CharField(blank=True, default='Santiago', max_length=200),
        ),
    ]
