# Generated by Django 2.2.1 on 2020-06-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0013_auto_20200620_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
