# Generated by Django 2.2.1 on 2020-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0014_auto_20200620_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='block',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='villa',
        ),
        migrations.AddField(
            model_name='lugar',
            name='otros',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
