# Generated by Django 2.2.1 on 2020-06-24 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0016_auto_20200620_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Provincia'),
        ),
    ]
