# Generated by Django 2.2.1 on 2020-08-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocata', '0001_initial'),
        ('carro', '0002_remove_carrocompra_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarroCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catidad', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('tocata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tocata.Tocata')),
            ],
        ),
    ]
