# Generated by Django 2.2.1 on 2020-08-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_itemcarrocompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrocompra',
            old_name='catidad',
            new_name='cantidad',
        ),
    ]
