# Generated by Django 2.2.1 on 2020-08-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_auto_20200825_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrocompra',
            name='tocata',
        ),
        migrations.AddField(
            model_name='carrocompra',
            name='item',
            field=models.ManyToManyField(blank=True, to='carro.ItemCarroCompra'),
        ),
    ]
