# Generated by Django 2.2.1 on 2020-08-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_auto_20200825_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrocompra',
            name='tocata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.Tocata'),
        ),
    ]
