# Generated by Django 2.2.1 on 2020-08-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0006_auto_20200826_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrocompra',
            name='cantidad',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
