# Generated by Django 2.2.1 on 2020-08-27 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0007_auto_20200826_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrocompra',
            name='fecha_actu',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcarrocompra',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
