# Generated by Django 2.2.1 on 2020-09-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0009_auto_20200828_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrocompra',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
