# Generated by Django 2.2.1 on 2020-08-15 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
        ('tocata', '0001_initial'),
        ('artista', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TocataAbierta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripción', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('asistentes_min', models.IntegerField()),
                ('flayer_original', models.ImageField(blank=True, default='fotos/defecto/imagen_original.jpg', upload_to='fotos/tocatas/%Y/%m/%d/')),
                ('flayer_1920_1280', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_1920_1280.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1280], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('flayer_380_507', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='fotos/defecto/imagen_380_507.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[380, 507], upload_to='fotos/lugares/%Y/%m/%d/')),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('suspendido', 'Suspendido'), ('confirmado', 'Confirmado'), ('borrado', 'Borrado')], default='publicado', max_length=2)),
                ('fecha_actu', models.DateTimeField(auto_now=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artista.Artista')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Comuna')),
                ('estilos', models.ManyToManyField(blank=True, to='artista.Estilo')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lugar.Region')),
                ('tocata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tocata.Tocata')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
