# Generated by Django 2.2.1 on 2020-09-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocataabierta', '0002_auto_20200816_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocataabierta',
            name='flayer_1920_1280',
        ),
        migrations.RemoveField(
            model_name='tocataabierta',
            name='flayer_original',
        ),
    ]
